name       : gscan2pdf
version    : 2.5.3
release    : 9
source     :
    - https://sourceforge.net/projects/gscan2pdf/files/gscan2pdf/2.5.3/gscan2pdf-2.5.3.tar.xz/download : dc5f8850895cc8a808d7ca3bfaed8c34f690b2353bd98d1e20923bf7c609f44b
license    : GPL-3.0-or-later
component  : multimedia.graphics
homepage   : http://gscan2pdf.sourceforge.net/
summary    : Produce PDFs or DjVus from scanned documents
description: |
    gscan2pdf is a GUI to ease the process of producing PDFs from scanned documents. You scan in one or several pages and create a PDF of selected pages.
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ImageMagick)
    - pkgconfig(libtiff-4)
    - pkgconfig(sane-backends)
    - pkgconfig(tesseract)
    - log4perl
    - perl-class-data-inheritable
    - perl-config-general
    - perl-data-uuid
    - perl-date-calc
    - perl-devel-stacktrace
    - perl-exporter-tiny
    - perl-filesys-df
    - perl-gettext
    - perl-glib
    - perl-goocanvas2
    - perl-gtk3
    - perl-gtk3-simplelist
    - perl-html-parser
    - perl-html-tagset
    - perl-image-sane
    - perl-io-string
    - perl-list-moreutils
    - perl-pdf-api2
    - perl-proc-processtable
    - perl-readonly
    - perl-set-intspan
    - perl-try-tiny
    - unpaper
    - xdg-utils
rundeps    :
    - log4perl
    - perl-class-data-inheritable
    - perl-config-general
    - perl-data-uuid
    - perl-date-calc
    - perl-devel-stacktrace
    - perl-exporter-tiny
    - perl-filesys-df
    - perl-gettext
    - perl-glib
    - perl-goocanvas2
    - perl-gtk3
    - perl-gtk3-simplelist
    - perl-html-parser
    - perl-html-tagset
    - perl-image-sane
    - perl-io-string
    - perl-list-moreutils
    - perl-pdf-api2
    - perl-proc-processtable
    - perl-readonly
    - perl-set-intspan
    - perl-try-tiny
    - tesseract
    - unpaper
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
