name       : gscan2pdf
version    : 2.5.6
release    : 11
source     :
    - https://netix.dl.sourceforge.net/project/gscan2pdf/gscan2pdf/2.5.6/gscan2pdf-2.5.6.tar.xz : df55f6ca8381af5bec77c5a62363c1328d937b5511cbca97badec912b50de872
license    : GPL-3.0-or-later
component  : multimedia.graphics
homepage   : http://gscan2pdf.sourceforge.net/
summary    : Produce PDFs or DjVus from scanned documents
description: |
    gscan2pdf is a GUI to ease the process of producing PDFs from scanned documents. You scan in one or several pages and create a PDF of selected pages.
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ImageMagick)
    - pkgconfig(libtiff-4)
    - pkgconfig(sane-backends)
    - pkgconfig(tesseract)
    - log4perl
    - perl-class-data-inheritable
    - perl-config-general
    - perl-data-uuid
    - perl-date-calc
    - perl-devel-stacktrace
    - perl-exporter-tiny
    - perl-filesys-df
    - perl-gettext
    - perl-glib
    - perl-goocanvas2
    - perl-gtk3
    - perl-gtk3-simplelist
    - perl-html-parser
    - perl-html-tagset
    - perl-image-sane
    - perl-io-string
    - perl-list-moreutils
    - perl-pdf-api2
    - perl-proc-processtable
    - perl-readonly
    - perl-set-intspan
    - perl-try-tiny
    - unpaper
    - xdg-utils
rundeps    :
    - imagemagick
    - libtiff-utils
    - log4perl
    - perl-class-data-inheritable
    - perl-config-general
    - perl-data-uuid
    - perl-date-calc
    - perl-devel-stacktrace
    - perl-exporter-tiny
    - perl-filesys-df
    - perl-gettext
    - perl-glib
    - perl-goocanvas2
    - perl-gtk3
    - perl-gtk3-simplelist
    - perl-html-parser
    - perl-html-tagset
    - perl-image-sane
    - perl-io-string
    - perl-list-moreutils
    - perl-pdf-api2
    - perl-proc-processtable
    - perl-readonly
    - perl-set-intspan
    - perl-try-tiny
    - tesseract
    - unpaper
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
